[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "tii-quantum"
version = "0.1.2"
description = "TII Quantum Computing Cloud Client"
authors = ["TII"]
license = "Apache License 2.0"
readme = "README.md"
homepage = "https://q-cloud.tii.ae"
repository = "https://github.com/q-hardware-tii/tii-quantum/"
documentation = "https://github.com/q-hardware-tii/tii-quantum/"
keywords = []
classifiers = [
  "Programming Language :: Python :: 3",
  "Topic :: Scientific/Engineering :: Physics",
]
packages = [{ include = "tii_quantum", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
requests = "^2.31.0"
tabulate = "^0.9.0"
packaging = "^26.1"
python-dateutil = "^2.9.0.post0"
rich = "^15.0.0"
qibo = "^0.3.4"
jupyter = { version = "^1.0.0", optional = true }
ipywidgets = { version = "^8.1.0", optional = true }

[tool.poetry.extras]
notebook = ["jupyter", "ipywidgets"]

[tool.poetry.group.test.dependencies]
pytest = ">=7.4.3,<10.0.0"
pytest-cov = "^6.0.0"
pylint = "^3.3.9"
responses = "^0.26.0"
jsf = "^0.11.2"

[tool.poe.tasks]
test = "pytest"
lint = "pylint --errors-only src"
lint-warnings = "pylint --exit-zero src"

[tool.pylint.reports]
output-format = "colorized"

[tool.pytest.ini_options]
testpaths = ['tests/']
filterwarnings = ['ignore::RuntimeWarning']
addopts = ['--cov=src/tii_quantum', '--cov-report=xml', '--cov-report=html']
